#assetic:
#  debug:          "%kernel.debug%"
#  use_controller: false
#  bundles:        [MopaBootstrapBundle, SurfnetStepupRaRaBundle]
#  #java: /usr/bin/java
#  node: "/usr/bin/node"
#  node_paths: ["/usr/lib/node_modules"]
#  filters:
#    cssrewrite: ~
#    less: ~
#    #closure:
#    #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
#    #yui_css:
#    #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
