framework:
  esi:             false
  translator:      { fallback: "%default_locale%" }
  secret:          "%secret%"
  form:            ~
  csrf_protection: ~
  validation:      { enable_annotations: true }
  default_locale:  "%default_locale%"
  trusted_hosts:   ~
  session:
    # handler_id set to null will use default session handler from php.ini
    handler_id:  ~
    name: sess_ra
    cookie_httponly: true
    cookie_secure: true
  fragments:       false
  http_method_override: true
  error_controller: Surfnet\StepupRa\RaBundle\Controller\ExceptionController
