framework:
  #esi:             ~
  translator:      { fallback: "%default_locale%" }
  secret:          "%secret%"
  router:
    resource: "%kernel.root_dir%/config/routing.yml"
    strict_requirements: ~
  form:            ~
  csrf_protection: ~
  validation:      { enable_annotations: true }
  templating:
    engines: ['twig', 'php']
  assets:
    version: "%asset_version%"
  default_locale:  "%default_locale%"
  trusted_hosts:   ~
  session:
    # handler_id set to null will use default session handler from php.ini
    handler_id:  ~
    name: sess_ra
    cookie_httponly: true
    cookie_secure: true
  fragments:       ~
  http_method_override: true