jms_translation:
  locales: "%locales%"
  configs:
    default:
      dirs: ["%kernel.root_dir%/../src", "%kernel.root_dir%", "%kernel.root_dir%/../vendor/surfnet/stepup-middleware-client-bundle", "%kernel.root_dir%/../vendor/surfnet/stepup-bundle"]
      output_dir: "%kernel.root_dir%/Resources/translations"
      ignored_domains: []
      excluded_names: ['*TestCase.php', '*Test.php']
      excluded_dirs: [cache, data, logs, Tests, vendor]
      extractors: []