knp_paginator:
  page_range: 5
  default_options:
    page_name: p
    sort_field_name: orderBy
    sort_direction_name: orderDirection
  template:
    pagination: pagination/sliding.html.twig
    sortable: pagination/sortable_link.html.twig
