surfnet_stepup_ra_ra:
  required_loa: "%authentication_context_class_ref%"
  enabled_second_factors: "%enabled_second_factors%"
  enabled_generic_second_factors: "%enabled_generic_second_factors%"
  session_lifetimes:
    max_absolute_lifetime: "%session_max_absolute_lifetime%"
    max_relative_lifetime: "%session_max_relative_lifetime%"
  self_service_url: "%self_service_url%"
