surfnet_stepup_middleware_client:
  authorisation:
    username: "%middleware_credentials_username%"
    password: "%middleware_credentials_password%"
  url:
    command_api: "%middleware_url_command_api%"
    api: "%middleware_url_api%"

when@smoketest:
  surfnet_stepup_middleware_client:
    authorisation:
      password: secret

when@test:
  surfnet_stepup_middleware_client:
    authorisation:
      password: secret
