twig:
  debug:            "%kernel.debug%"
  strict_variables: "%kernel.debug%"
  exception_controller: SurfnetStepupRaRaBundle:Exception:show
  globals:
    global_view_parameters: "@ra.service.global_view_parameters"
