twig:
  paths:
    '%kernel.project_dir%/templates': SurfnetStepupRaRa
  debug:            "%kernel.debug%"
  strict_variables: "%kernel.debug%"
  exception_controller: SurfnetStepupRaRaBundle:Exception:show
  date:
    format: "%date_format%"
    timezone: "%date_timezone%"
  globals:
    global_view_parameters: "@ra.service.global_view_parameters"
  form_themes: ['bootstrap_3_horizontal_layout.html.twig', 'form/fields.html.twig']
