when@dev:
    web_profiler:
        toolbar: true
        intercept_redirects: false

when@test: &testTemplate
    web_profiler:
        toolbar: false
        intercept_redirects: false
when@smoketest: *testTemplate

