ra_saml_metadata:
    path: /authentication/metadata
    methods: [GET]
    defaults: { _controller: SurfnetStepupRaRaBundle:Saml:metadata }

ra_serviceprovider_consume_assertion:
    path: /authentication/consume-assertion
    methods: [POST]
    defaults: { _controller: SurfnetStepupRaRaBundle:Saml:consumeAssertion }

ra_locations_manage:
    path:     /locations
    methods: [GET, POST]
    defaults: { _controller: SurfnetStepupRaRaBundle:RaLocation:manage }

ra_location_create:
    path:     /locations/create/{institution}
    methods: [GET, POST]
    defaults: { _controller: SurfnetStepupRaRaBundle:RaLocation:create }

ra_location_change:
    path:     /locations/{locationId}/change
    methods: [GET, POST]
    defaults: { _controller: SurfnetStepupRaRaBundle:RaLocation:change }

ra_location_remove:
    path:     /locations/remove
    methods: [POST]
    defaults: { _controller: SurfnetStepupRaRaBundle:RaLocation:remove }

ra_second_factors_search:
    path:     /second-factors
    methods: [GET, POST]
    defaults: { _controller: SurfnetStepupRaRaBundle:SecondFactor:search }

ra_second_factor_revoke:
    path:     /second-factors/revoke
    methods:  [POST]
    defaults: { _controller: SurfnetStepupRaRaBundle:SecondFactor:revoke }

ra_second_factor_auditlog:
    path:     /second-factors/{identityId}/auditlog
    methods:  [GET]
    defaults: { _controller: SurfnetStepupRaRaBundle:SecondFactor:auditLog }

ra_vetting_search:
    path:     /
    methods: [GET, POST]
    defaults: { _controller: SurfnetStepupRaRaBundle:Vetting:startProcedure }

ra_vetting_cancel:
    path:     /vetting-procedure/{procedureId}/cancel
    methods: [POST]
    defaults: { _controller: SurfnetStepupRaRaBundle:Vetting:cancelProcedure }

ra_vetting_yubikey_verify:
    path:     /vetting-procedure/{procedureId}/verify-yubikey
    methods:  [GET, POST]
    defaults: { _controller: SurfnetStepupRaRaBundle:Vetting/Yubikey:verify }

ra_vetting_sms_send_challenge:
    path:     /vetting-procedure/{procedureId}/send-sms-challenge
    methods:  [GET, POST]
    defaults: { _controller: SurfnetStepupRaRaBundle:Vetting/Sms:sendChallenge }

ra_vetting_sms_prove_possession:
    path:     /vetting-procedure/{procedureId}/verify-sms-challenge
    methods:  [GET,POST]
    defaults: { _controller: SurfnetStepupRaRaBundle:Vetting/Sms:provePossession }

ra_vetting_gssf_initiate:
    path: /vetting-procedure/{procedureId}/gssf/{provider}/initiate-verification
    methods: [GET]
    defaults: { _controller: SurfnetStepupRaRaBundle:Vetting/Gssf:initiate }

ra_vetting_gssf_authenticate:
    path: /vetting-procedure/{procedureId}/gssf/{provider}/authenticate
    methods: [POST]
    defaults: { _controller: SurfnetStepupRaRaBundle:Vetting/Gssf:authenticate }

ra_vetting_gssf_verify:
    path: /vetting-procedure/gssf/{provider}/verify
    methods: [POST]
    defaults: { _controller: SurfnetStepupRaRaBundle:Vetting/Gssf:verify }

ra_vetting_gssf_metadata:
    path: /vetting-procedure/gssf/{provider}/metadata
    methods: [GET]
    defaults: { _controller: SurfnetStepupRaRaBundle:Vetting/Gssf:metadata }

ra_vetting_verify_identity:
    path:     /vetting-procedure/{procedureId}/verify-identity
    methods:  [GET, POST]
    defaults: { _controller: SurfnetStepupRaRaBundle:Vetting:verifyIdentity }

ra_vetting_completed:
    path:     /vetting-procedure/{procedureId}/completed
    methods:  [GET]
    defaults: { _controller: SurfnetStepupRaRaBundle:Vetting:vettingCompleted }

ra_management_manage:
    path:     /management/ra
    methods:  [GET]
    defaults: { _controller: SurfnetStepupRaRaBundle:RaManagement:manage }

ra_management_ra_candidate_search:
    path:     /management/search-ra-candidate
    methods:  [GET, POST]
    defaults: { _controller: SurfnetStepupRaRaBundle:RaManagement:raCandidateSearch }

ra_management_create_ra:
    path:     /management/create-ra/{identityId}
    methods:  [GET, POST]
    defaults: { _controller: SurfnetStepupRaRaBundle:RaManagement:createRa }

ra_management_amend_ra_information:
    path:     /management/amend-ra-information/{identityId}/{raInstitution}
    methods:  [GET, POST]
    defaults: { _controller: SurfnetStepupRaRaBundle:RaManagement:amendRaInformation }

ra_management_retract_registration_authority:
    path:     /management/retract-registration-authority/{identityId}/{raInstitution}
    methods:  [GET, POST]
    defaults: { _controller: SurfnetStepupRaRaBundle:RaManagement:retractRegistrationAuthority }

institution-configuration:
    path: /institution-configuration
    methods: [GET, POST]
    defaults:
        _controller: SurfnetStepupRaRaBundle:Raa:institutionConfiguration

ra_switch_locale:
    path:     /switch-locale
    methods:  [POST]
    defaults: { _controller: SurfnetStepupRaRaBundle:Locale:switchLocale }
    requirements:
        'return-url': '.+'

ra_security_session_expired:
    path: /authentication/session-expired
    methods: [GET]
    defaults:
        _controller: SurfnetStepupRaRaBundle:Security:sessionExpired

ra_profile:
    path: /profile
    methods: [GET]
    defaults:
        _controller: SurfnetStepupRaRaBundle:Profile:profile
