ra_saml_metadata:
    path: /authentication/metadata
    methods: [GET]
    defaults: { _controller: \Surfnet\StepupRa\RaBundle\Controller\SamlController::metadata }

ra_serviceprovider_consume_assertion:
    path: /authentication/consume-assertion
    methods: [POST]
    defaults: { _controller: \Surfnet\StepupRa\RaBundle\Controller\SamlController::consumeAssertion }

ra_locations_manage:
    path:     /locations
    methods: [GET, POST]
    defaults: { _controller: Surfnet\StepupRa\RaBundle\Controller\RaLocationController::manage }

ra_location_create:
    path:     /locations/create/{institution}
    methods: [GET, POST]
    defaults: { _controller: Surfnet\StepupRa\RaBundle\Controller\RaLocationController::create }

ra_location_change:
    path:     /locations/{locationId}/change
    methods: [GET, POST]
    defaults: { _controller: Surfnet\StepupRa\RaBundle\Controller\RaLocationController::change }

ra_location_remove:
    path:     /locations/remove
    methods: [POST]
    defaults: { _controller: Surfnet\StepupRa\RaBundle\Controller\RaLocationController::remove }

ra_second_factors_search:
    path:     /second-factors
    methods: [GET, POST]
    defaults: { _controller: Surfnet\StepupRa\RaBundle\Controller\SecondFactorController::search}

ra_second_factor_revoke:
    path:     /second-factors/revoke
    methods:  [POST]
    defaults: { _controller: Surfnet\StepupRa\RaBundle\Controller\SecondFactorController::revoke }

ra_second_factor_auditlog:
    path:     /second-factors/{identityId}/auditlog
    methods:  [GET]
    defaults: { _controller: Surfnet\StepupRa\RaBundle\Controller\SecondFactorController::auditLog }

ra_recovery_tokens_search:
    path:     /recovery-tokens
    methods: [GET, POST]
    defaults: { _controller: Surfnet\StepupRa\RaBundle\Controller\RecoveryTokenController::search }

ra_recovery_tokens_revoke:
    path:     /recovery-tokens/revoke
    methods:  [POST]
    defaults: { _controller: Surfnet\StepupRa\RaBundle\Controller\RecoveryTokenController::revoke }

ra_recovery_tokens_auditlog:
    path: /recovery-tokens/{identityId}/auditlog
    methods: [ GET ]
    defaults: { _controller: Surfnet\StepupRa\RaBundle\Controller\SecondFactorController::auditLog }

ra_vetting_search:
    path:     /
    methods: [GET, POST]
    defaults: { _controller: Surfnet\StepupRa\RaBundle\Controller\VettingController::startProcedure }

ra_vetting_cancel:
    path:     /vetting-procedure/{procedureId}/cancel
    methods: [POST]
    defaults: { _controller: Surfnet\StepupRa\RaBundle\Controller\VettingController::cancelProcedure }

ra_vetting_yubikey_verify:
    path:     /vetting-procedure/{procedureId}/verify-yubikey
    methods:  [GET, POST]
    defaults: { _controller: Surfnet\StepupRa\RaBundle\Controller\Vetting\YubikeyController::verify }

ra_vetting_sms_send_challenge:
    path:     /vetting-procedure/{procedureId}/send-sms-challenge
    methods:  [GET, POST]
    defaults: { _controller: \Surfnet\StepupRa\RaBundle\Controller\Vetting\SmsController::sendChallenge }

ra_vetting_sms_prove_possession:
    path:     /vetting-procedure/{procedureId}/verify-sms-challenge
    methods:  [GET,POST]
    defaults: { _controller: \Surfnet\StepupRa\RaBundle\Controller\Vetting\SmsController::provePossession}

ra_vetting_gssf_initiate:
    path: /vetting-procedure/{procedureId}/gssf/{provider}/initiate-verification
    methods: [GET]
    defaults: { _controller: \Surfnet\StepupRa\RaBundle\Controller\Vetting\GssfController::initiate }

ra_vetting_gssf_authenticate:
    path: /vetting-procedure/{procedureId}/gssf/{provider}/authenticate
    methods: [POST]
    defaults: { _controller: \Surfnet\StepupRa\RaBundle\Controller\Vetting\GssfController::authenticate}

ra_vetting_gssf_verify:
    path: /vetting-procedure/gssf/{provider}/verify
    methods: [POST]
    defaults: { _controller: \Surfnet\StepupRa\RaBundle\Controller\Vetting\GssfController::verify }

ra_vetting_gssf_metadata:
    path: /vetting-procedure/gssf/{provider}/metadata
    methods: [GET]
    defaults: { _controller: \Surfnet\StepupRa\RaBundle\Controller\Vetting\GssfController::metadata}

ra_vetting_verify_identity:
    path:     /vetting-procedure/{procedureId}/verify-identity
    methods:  [GET, POST]
    defaults: { _controller: \Surfnet\StepupRa\RaBundle\Controller\VettingController::verifyIdentity }

ra_vetting_completed:
    path:     /vetting-procedure/{procedureId}/completed
    methods:  [GET]
    defaults: { _controller: \Surfnet\StepupRa\RaBundle\Controller\VettingController::vettingCompleted}

ra_management_manage:
    path:     /management/ra
    methods:  [GET]
    defaults: { _controller: \Surfnet\StepupRa\RaBundle\Controller\RaManagementController::manage }

ra_management_ra_candidate_search:
    path:     /management/search-ra-candidate
    methods:  [GET, POST]
    defaults: { _controller: \Surfnet\StepupRa\RaBundle\Controller\RaManagementController::raCandidateSearch }

ra_management_create_ra:
    path:     /management/create-ra/{identityId}
    methods:  [GET, POST]
    defaults: { _controller: \Surfnet\StepupRa\RaBundle\Controller\RaManagementController::createRa }

ra_management_amend_ra_information:
    path:     /management/amend-ra-information/{identityId}/{raInstitution}
    methods:  [GET, POST]
    defaults: { _controller: \Surfnet\StepupRa\RaBundle\Controller\RaManagementController::amendRaInformation}

ra_management_retract_registration_authority:
    path:     /management/retract-registration-authority/{identityId}/{raInstitution}
    methods:  [GET, POST]
    defaults: { _controller: \Surfnet\StepupRa\RaBundle\Controller\RaManagementController::retractRegistrationAuthority }

institution-configuration:
    path: /institution-configuration
    methods: [GET, POST]
    defaults:
        _controller: \Surfnet\StepupRa\RaBundle\Controller\RaaController::institutionConfiguration

vetting_type_hint:
    path: /vetting-type-hint
    methods: [GET, POST]
    defaults:
        _controller: \Surfnet\StepupRa\RaBundle\Controller\VettingTypeHintController::vettingTypeHint

ra_switch_locale:
    path:     /switch-locale
    methods:  [POST]
    defaults: { _controller: \Surfnet\StepupRa\RaBundle\Controller\LocaleController::switchLocale}
    requirements:
        'return-url': '.+'

ra_security_session_expired:
    path: /authentication/session-expired
    methods: [GET]
    defaults:
        _controller: \Surfnet\StepupRa\RaBundle\Controller\SecurityController::sessionExpired

ra_profile:
    path: /profile
    methods: [GET]
    defaults:
        _controller: \Surfnet\StepupRa\RaBundle\Controller\ProfileController::profile
