ra_saml_metadata:
    path: /authentication/metadata
    methods: [GET]
    defaults: { _controller: SurfnetStepupRaRaBundle:Saml:metadata }

ra_serviceprovider_consume_assertion:
    path: /authentication/consume-assertion
    methods: [POST]
    defaults: { _controller: SurfnetStepupRaRaBundle:Saml:consumeAssertion }

ra_vetting_search:
    path:     /
    methods: [GET, POST]
    defaults: { _controller: SurfnetStepupRaRaBundle:Vetting:startProcedure }

ra_second_factors_search:
    path:     /second-factors
    methods: [GET, POST]
    defaults: { _controller: SurfnetStepupRaRaBundle:SecondFactor:search }

ra_vetting_yubikey_verify:
    path: /vetting-procedure/{procedureId}/verify-yubikey
    methods: [GET, POST]
    defaults: { _controller: SurfnetStepupRaRaBundle:Vetting/Yubikey:verify }

ra_vetting_sms_send_challenge:
    path:     /vetting-procedure/{procedureId}/send-sms-challenge
    methods:  [GET, POST]
    defaults: { _controller: SurfnetStepupRaRaBundle:Vetting/Sms:sendChallenge }

ra_vetting_sms_prove_possession:
    path:     /vetting-procedure/{procedureId}/verify-sms-challenge
    methods:  [GET,POST]
    defaults: { _controller: SurfnetStepupRaRaBundle:Vetting/Sms:provePossession }

ra_vetting_gssf_initiate:
    path: /vetting-procedure/{procedureId}/gssf/{provider}/initiate-verification
    methods: [GET]
    defaults: { _controller: SurfnetStepupRaRaBundle:Vetting/Gssf:initiate }

ra_vetting_gssf_authenticate:
    path: /vetting-procedure/{procedureId}/gssf/{provider}/authenticate
    methods: [POST]
    defaults: { _controller: SurfnetStepupRaRaBundle:Vetting/Gssf:authenticate }

ra_vetting_gssf_verify:
    path: /vetting-procedure/gssf/{provider}/verify
    methods: [POST]
    defaults: { _controller: SurfnetStepupRaRaBundle:Vetting/Gssf:verify }

ra_vetting_gssf_metadata:
    path: /vetting-procedure/gssf/{provider}/metadata
    methods: [GET, POST]
    defaults: { _controller: SurfnetStepupRaRaBundle:Vetting/Gssf:metadata }

ra_vetting_verify_identity:
    path:     /vetting-procedure/{procedureId}/verify-identity
    methods:  [GET, POST]
    defaults: { _controller: SurfnetStepupRaRaBundle:Vetting:verifyIdentity }

ra_vetting_completed:
    path:     /vetting-procedure/{procedureId}/completed
    methods:  [GET]
    defaults: { _controller: SurfnetStepupRaRaBundle:Vetting:vettingCompleted }
