services:
    # To be compatible with loading services from the container instead of using DI, TODO, Utilize DI throughout the
    # application.
    _defaults: { public: true }

    logger:
      alias: 'monolog.logger'
      public: true

    ra.service.command:
        class: Surfnet\StepupRa\RaBundle\Service\CommandService
        arguments:
            - "@surfnet_stepup_middleware_client.service.command"
            - "@security.token_storage"

    # Forms
    ra.form.type.anchor:
        class: Surfnet\StepupRa\RaBundle\Form\Type\AnchorType
        tags: [{ name: form.type, alias: anchor }]

    ra.form.type.start_vetting_procedure:
        class: Surfnet\StepupRa\RaBundle\Form\Type\StartVettingProcedureType
        tags: [{ name: form.type, alias: ra_start_vetting_procedure }]

    ra.form.type.prove_yubikey_possession:
        class: Surfnet\StepupRa\RaBundle\Form\Type\VerifyYubikeyPublicIdType
        tags: [{ name: form.type, alias: ra_verify_yubikey_public_id }]

    ra.form.type.verify_identity:
        class: Surfnet\StepupRa\RaBundle\Form\Type\VerifyIdentityType
        tags: [{ name: form.type, alias: ra_verify_identity }]

    ra.form.type.send_sms_challenge:
        class: Surfnet\StepupRa\RaBundle\Form\Type\SendSmsChallengeType
        tags: [{ name: form.type, alias: ra_send_sms_challenge }]

    ra.form.type.verify_sms_challenge:
        class: Surfnet\StepupRa\RaBundle\Form\Type\VerifyPhoneNumberType
        tags: [{ name: form.type, alias: ra_verify_phone_number }]

    ra.form.type.search_ra_candidates:
        class: Surfnet\StepupRa\RaBundle\Form\Type\SearchRaCandidatesType
        tags: [{ name: form.type, alias: ra_search_ra_candidates }]

    ra.form.type.ra_create_ra_location:
        class: Surfnet\StepupRa\RaBundle\Form\Type\CreateRaLocationType
        tags: [{ name: form.type, alias: ra_create_ra_location }]

    ra.form.type.ra_change_ra_location:
        class: Surfnet\StepupRa\RaBundle\Form\Type\ChangeRaLocationType
        tags: [{ name: form.type, alias: ra_change_ra_location }]

    ra.form.type.ra_remove_ra_location:
        class: Surfnet\StepupRa\RaBundle\Form\Type\RemoveRaLocationType
        tags: [{ name: form.type, alias: ra_remove_ra_location }]

    ra.form.type.search_ra_second_factors:
        class: Surfnet\StepupRa\RaBundle\Form\Type\SearchRaSecondFactorsType
        arguments:
            - "@ra.form.extension.second_factor_type_choice_list"
        tags: [{ name: form.type, alias: ra_search_ra_second_factors }]

    ra.form.type.search_recovery_tokens:
        class: Surfnet\StepupRa\RaBundle\Form\Type\SearchRecoveryTokensType
        tags: [{ name: form.type, alias: ra_search_ra_second_factors }]

    ra.form.type.ra_revoke_second_factor:
        class: Surfnet\StepupRa\RaBundle\Form\Type\RevokeSecondFactorType
        tags: [{ name: form.type, alias: ra_revoke_second_factor }]

    ra.form.type.sraa_institution_select:
        class: Surfnet\StepupRa\RaBundle\Form\Type\InstitutionSelectionType
        arguments:
            - "@ra.form.extension.institution_listing_choice_list"
        tags: [{ name: form.type, alias: sraa_institution_select }]

    ra.form.type.management.create_ra:
        class: Surfnet\StepupRa\RaBundle\Form\Type\CreateRaType
        tags: [{ name: form.type, alias: ra_management_create_ra }]

    ra.form.type.management.amend_ra_info:
        class: Surfnet\StepupRa\RaBundle\Form\Type\AmendRegistrationAuthorityInformationType
        tags: [{ name: form.type, alias: ra_management_amend_ra_info }]

    ra.form.type.management.change_role:
        class: Surfnet\StepupRa\RaBundle\Form\Type\ChangeRaRoleType
        tags: [{ name: form.type, alias: ra_management_change_ra_role }]

    ra.form.type.management.retract_registration_authority:
        class: Surfnet\StepupRa\RaBundle\Form\Type\RetractRegistrationAuthorityType
        tags: [{ name: form.type, alias: ra_management_retract_registration_authority }]

    ra.form.type.initiate_gssf:
        class: Surfnet\StepupRa\RaBundle\Form\Type\InitiateGssfType
        arguments:
            - "@router"
        tags: [{ name: form.type, alias: ra_initiate_gssf }]

    # Form Extensions
    ra.form.extension.institution_listing_choice_list:
        class: Surfnet\StepupRa\RaBundle\Form\Extension\InstitutionListingChoiceList
        arguments:
            - "@surfnet_stepup_middleware_client.identity.service.institution_listing"

    ra.form.extension.second_factor_type_choice_list:
        class: Surfnet\StepupRa\RaBundle\Form\Extension\SecondFactorTypeChoiceList
        arguments:
            - "@surfnet_stepup.service.second_factor_type"
            - "@surfnet_stepup.service.second_factor_type_translator"
            - "@logger"

    # Services
    ra.service.vetting:
        class: Surfnet\StepupRa\RaBundle\Service\VettingService
        arguments:
            - "@surfnet_stepup.service.sms_second_factor"
            - "@ra.service.yubikey_second_factor"
            - "@ra.service.gssf"
            - "@ra.service.command"
            - "@ra.repository.vetting_procedure"
            - "@translator"
            - "@ra.service.identity"
            - "@surfnet_stepup.service.second_factor_type"
            - "@surfnet_stepup_middleware_client.identity.service.second_factor"

    ra.service.yubikey:
        public: false
        class: Surfnet\StepupRa\RaBundle\Service\YubikeyService
        arguments:
            - "@surfnet_stepup.guzzle.gateway_api"
            - "@logger"

    ra.service.yubikey_second_factor:
        public: true
        class: Surfnet\StepupRa\RaBundle\Service\YubikeySecondFactorService
        arguments:
            - "@ra.service.yubikey"
            - "@logger"

    ra.service.gssf:
        class: Surfnet\StepupRa\RaBundle\Service\GssfService
        arguments:
            - "@ra.service.gssf.sessionbag"

    ra.service.gssf.sessionbag:
        class: Symfony\Component\HttpFoundation\Session\Attribute\NamespacedAttributeBag
        factory: ['@session', 'getBag']
        arguments: ['ra.service.gssf']

    ra.service.gssf.namespaced_attribute_bag:
        public: false
        class: Symfony\Component\HttpFoundation\Session\Attribute\NamespacedAttributeBag
        arguments:
            - '__ra.service.gssf__'
            - '/'
        calls:
            - [setName, ['ra.service.gssf']]

    ra.service.audit_log:
        class: Surfnet\StepupRa\RaBundle\Service\AuditLogService
        arguments:
            - "@surfnet_stepup_middleware_client.identity.service.audit_log"
            - "@logger"

    ra.service.identity:
        class: Surfnet\StepupRa\RaBundle\Service\IdentityService
        arguments:
            - "@surfnet_stepup_middleware_client.identity.service.identity"
            - "@ra.service.command"
            - "@security.token_storage"
            - "@logger"

    ra.service.institution_configuration_options:
        class: Surfnet\StepupRa\RaBundle\Service\InstitutionConfigurationOptionsService
        arguments:
            - "@surfnet_stepup_middleware_client.configuration.service.institution_configuration_options"

    ra.service.locale_provider:
        class: Surfnet\StepupRa\RaBundle\Service\LocaleProviderService
        arguments:
            - "@security.token_storage"

    ra.service.ra_candidate:
        class: Surfnet\StepupRa\RaBundle\Service\RaCandidateService
        arguments:
            - "@surfnet_stepup_middleware_client.identity.service.ra_candidate"
            - "@ra.service.command"
            - "@logger"
            - "@surfnet_stepup.service.second_factor_type"

    ra.service.ra_location:
        class: Surfnet\StepupRa\RaBundle\Service\RaLocationService
        arguments:
            - "@surfnet_stepup_middleware_client.configuration.service.ra_location"
            - "@ra.service.command"
            - "@logger"

    ra.service.ra_listing:
        class: Surfnet\StepupRa\RaBundle\Service\RaListingService
        arguments:
            - "@surfnet_stepup_middleware_client.identity.service.ra_listing"
            - "@logger"

    ra.service.ra_second_factor_exporter:
        class: Surfnet\StepupRa\RaBundle\Service\RaSecondFactorExport
        arguments:
            - "@logger"

    ra.service.ra_second_factor:
        class: Surfnet\StepupRa\RaBundle\Service\RaSecondFactorService
        arguments:
            - "@surfnet_stepup_middleware_client.identity.service.ra_second_factor"
            - "@ra.service.command"
            - "@ra.service.ra_second_factor_exporter"
            - "@logger"

    ra.service.ra:
        class: Surfnet\StepupRa\RaBundle\Service\RaService
        arguments:
            - "@ra.service.command"
            - "@logger"

    ra.service.second_factor:
        class: Surfnet\StepupRa\RaBundle\Service\SecondFactorService
        arguments:
            - "@surfnet_stepup_middleware_client.identity.service.second_factor"
            - "@logger"

    ra.service.global_view_parameters:
        class: Surfnet\StepupRa\RaBundle\Service\GlobalViewParameters
        arguments:
            - "@translator"
            - "%locales%"
            - "%support_url%"

    ra.service.profile:
        class: Surfnet\StepupRa\RaBundle\Service\ProfileService
        arguments:
            - "@surfnet_stepup_middleware_client.identity.service.profile"
            - "@logger"

    ra.service.institution_listing:
        class: Surfnet\StepupRa\RaBundle\Service\InstitutionListingService
        arguments:
            - "@surfnet_stepup_middleware_client.identity.service.institution_listing"

    Surfnet\StepupRa\RaBundle\Service\RecoveryTokenService:
        arguments:
            - "@ra.service.command"
            - '@Surfnet\StepupMiddlewareClientBundle\Identity\Service\RecoveryTokenService'
            - '@logger'

    Surfnet\StepupRa\RaBundle\Service\VettingTypeHintService:
        arguments:
            - '@ra.service.command'
            - '@Surfnet\StepupMiddlewareClientBundle\Identity\Service\VettingTypeHintService'
            - '@logger'

    # Repositories
    ra.repository.vetting_procedure:
        class: Surfnet\StepupRa\RaBundle\Repository\SessionVettingProcedureRepository
        arguments:
            - "@session"
            - 'Surfnet/StepupRa/RaBundle/Repository/VettingProcedureRepository'

    #Logger
    ra.procedure_logger:
        class: Surfnet\StepupRa\RaBundle\Logger\ProcedureAwareLogger
        arguments:
            - "@logger"

    # Listeners
    ra.event_listener.locale:
        class: Surfnet\StepupRa\RaBundle\EventListener\LocaleListener
        arguments: [ "@security.token_storage", "@translator" ]
        tags: [{ name: kernel.event_subscriber }]

    ra.event_listener.locale_cookie:
        class: Surfnet\StepupBundle\EventListener\LocaleCookieListener
        arguments:
            - "@surfnet_stepup.locale_cookie_helper"
            - "@ra.service.locale_provider"
            - "@logger"
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse, priority: 6 }

    ra.exception_listener.inconsistent_state:
        class: Surfnet\StepupRa\RaBundle\EventListener\InconsistentStateListener
        arguments:
            - "@logger"
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    # Twig
    ra.twig.second_factor_type:
        class: Surfnet\StepupRa\RaBundle\Twig\Extensions\Extension\SecondFactorType
        arguments:
            - "@surfnet_stepup.service.second_factor_type_translator"
        tags:
            - { name : twig.extension }

    # Controller
    ra.controller.profile:
        class: Surfnet\StepupRa\RaBundle\Controller\ProfileController
        arguments:
            - "@ra.service.profile"
        tags: ['controller.service_arguments']

    Surfnet\StepupRa\RaBundle\Controller\RecoveryTokenController:
        arguments:
            - '@Surfnet\StepupRa\RaBundle\Service\RecoveryTokenService'
            - '@Knp\Component\Pager\PaginatorInterface'
            - '@security.token_storage'
            - "@logger"
        tags: ['controller.service_arguments']

    Surfnet\StepupRa\RaBundle\Controller\VettingTypeHintController:
        arguments:
            - '@logger'
            - '@ra.service.institution_listing'
            - '@ra.service.profile'
            - '@Surfnet\StepupRa\RaBundle\Service\VettingTypeHintService'
            - '%locales%'
        tags: ['controller.service_arguments']
