imports:
    - { resource: samlstepupproviders_parameters.yml }

surfnet_stepup_ra_saml_stepup_provider:
    routes:
        consume_assertion: ra_vetting_gssf_verify
        metadata: ra_vetting_gssf_metadata
    providers:
        tiqr:
            hosted:
                service_provider:
                    public_key: %gssp_tiqr_sp_publickey%
                    private_key: %gssp_tiqr_sp_privatekey%
                metadata:
                    public_key: %gssp_tiqr_metadata_publickey%
                    private_key: %gssp_tiqr_metadata_privatekey%
            remote:
                entity_id: %gssp_tiqr_remote_entity_id%
                sso_url: %gssp_tiqr_remote_sso_url%
                certificate: %gssp_tiqr_remote_certificate%
        biometric:
            hosted:
                service_provider:
                    public_key: %gssp_biometric_sp_publickey%
                    private_key: %gssp_biometric_sp_privatekey%
                metadata:
                    public_key: %gssp_biometric_metadata_publickey%
                    private_key: %gssp_biometric_metadata_privatekey%
            remote:
                entity_id: %gssp_biometric_remote_entity_id%
                sso_url: %gssp_biometric_remote_sso_url%
                certificate: %gssp_biometric_remote_certificate%
