imports:
    - { resource: samlstepupproviders_parameters.yml }

surfnet_stepup_ra_saml_stepup_provider:
    routes:
        consume_assertion: %gssp_routes_consume_assertion%
        metadata: %gssp_routes_metadata%
    providers:
        tiqr:
            hosted:
                service_provider:
                    public_key: %gssp_tiqr_sp_publickey%
                    private_key: %gssp_tiqr_sp_privatekey%
                metadata:
                    public_key: %gssp_tiqr_metadata_publickey%
                    private_key: %gssp_tiqr_metadata_privatekey%
            remote:
                entity_id: %gssp_tiqr_remote_entity_id%
                sso_url: %gssp_tiqr_remote_sso_url%
                certificate: %gssp_tiqr_remote_certificate%
