security:
    providers:
        middleware:
            id: ra.service.identity

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/|^/_trans(/|$)
            security: false

        default:
            pattern: ^/authentication/(metadata|session-expired)$
            logout_on_user_change: true
            anonymous: ~

        monitor:
            pattern: ^/(info|health)$
            security: false

        csp_report:
            pattern: ^/csp/report$
            security: false

        saml_based:
            saml: true
            logout_on_user_change: true
            logout:
                path: /logout
                target: "%logout_redirect_url%"
                invalidate_session: true
                csrf_token_generator: security.csrf.token_manager
                csrf_parameter: 't'
                csrf_token_id: 'registration_authority_logout_token'

    role_hierarchy:
        ROLE_SRAA: ROLE_RAA
        ROLE_RAA: ROLE_RA
        ROLE_RA: ROLE_USER

    access_control:
        - { path: ^/authentication, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/, roles: ROLE_RA, requires_channel: https }
