security:
    providers:
        middleware:
            id: ra.service.identity

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/|^/_trans(/|$)
            security: false

        default:
            pattern: ^/authentication/(metadata|session-expired)$
            anonymous: ~

        saml_based:
            saml: true
            logout:
                path: /logout
                success_handler: "ra.security.authentication.handler.logout_success"
                invalidate_session: true
                csrf_token_generator: form.csrf_provider
                csrf_parameter: 't'
                csrf_token_id: 'registration_authority_logout_token'

    role_hierarchy:
        ROLE_SRAA: ROLE_RAA
        ROLE_RAA: ROLE_RA
        ROLE_RA: ROLE_USER

    access_control:
        - { path: ^/authentication, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/, roles: ROLE_RA, requires_channel: https }
