imports:
    - { resource: samlstepupproviders_parameters.yaml }

surfnet_stepup_ra_saml_stepup_provider:
    routes:
        consume_assertion: ra_vetting_gssf_verify
        metadata: ra_vetting_gssf_metadata

    providers:
        tiqr:
            hosted:
                service_provider:
                    public_key: "%gssp_tiqr_sp_publickey%"
                    private_key: "%gssp_tiqr_sp_privatekey%"
                metadata:
                    public_key: "%gssp_tiqr_metadata_publickey%"
                    private_key: "%gssp_tiqr_metadata_privatekey%"
            remote:
                entity_id: "%gssp_tiqr_remote_entity_id%"
                sso_url: "%gssp_tiqr_remote_sso_url%"
                certificate: "%gssp_tiqr_remote_certificate%"
            view_config:
                title: "%gssp_tiqr_title%"
                page_title: "%gssp_tiqr_page_title%"
                explanation: "%gssp_tiqr_explanation%"
                initiate: "%gssp_tiqr_initiate%"
                gssf_id_mismatch: "%gssp_tiqr_gssf_id_mismatch%"
        webauthn:
            hosted:
                service_provider:
                    public_key: "%gssp_webauthn_sp_publickey%"
                    private_key: "%gssp_webauthn_sp_privatekey%"
                metadata:
                    public_key: "%gssp_webauthn_metadata_publickey%"
                    private_key: "%gssp_webauthn_metadata_privatekey%"
            remote:
                entity_id: "%gssp_webauthn_remote_entity_id%"
                sso_url: "%gssp_webauthn_remote_sso_url%"
                certificate: "%gssp_webauthn_remote_certificate%"
            view_config:
                title: "%gssp_webauthn_title%"
                page_title: "%gssp_webauthn_page_title%"
                explanation: "%gssp_webauthn_explanation%"
                initiate: "%gssp_webauthn_initiate%"
                gssf_id_mismatch: "%gssp_webauthn_gssf_id_mismatch%"
        azuremfa:
            hosted:
                service_provider:
                    public_key: "%gssp_azuremfa_sp_publickey%"
                    private_key: "%gssp_azuremfa_sp_privatekey%"
                metadata:
                    public_key: "%gssp_azuremfa_metadata_publickey%"
                    private_key: "%gssp_azuremfa_metadata_privatekey%"
            remote:
                entity_id: "%gssp_azuremfa_remote_entity_id%"
                sso_url: "%gssp_azuremfa_remote_sso_url%"
                certificate: "%gssp_azuremfa_remote_certificate%"
            view_config:
                title: "%gssp_azuremfa_title%"
                page_title: "%gssp_azuremfa_page_title%"
                explanation: "%gssp_azuremfa_explanation%"
                initiate: "%gssp_azuremfa_initiate%"
                gssf_id_mismatch: "%gssp_azuremfa_gssf_id_mismatch%"
        demo_gssp:
            hosted:
                service_provider:
                    public_key: "%gssp_demo_gssp_sp_publickey%"
                    private_key: "%gssp_demo_gssp_sp_privatekey%"
                metadata:
                    public_key: "%gssp_demo_gssp_metadata_publickey%"
                    private_key: "%gssp_demo_gssp_metadata_privatekey%"
            remote:
                entity_id: "%gssp_demo_gssp_remote_entity_id%"
                sso_url: "%gssp_demo_gssp_remote_sso_url%"
                certificate: "%gssp_demo_gssp_remote_certificate%"
            view_config:
                title: "%gssp_demo_gssp_title%"
                page_title: "%gssp_demo_gssp_page_title%"
                explanation: "%gssp_demo_gssp_explanation%"
                initiate: "%gssp_demo_gssp_initiate%"
                gssf_id_mismatch: "%gssp_demo_gssp_gssf_id_mismatch%"
        demo_gssp_2:
            hosted:
                service_provider:
                    public_key: "%gssp_demo_gssp_2_sp_publickey%"
                    private_key: "%gssp_demo_gssp_2_sp_privatekey%"
                metadata:
                    public_key: "%gssp_demo_gssp_2_metadata_publickey%"
                    private_key: "%gssp_demo_gssp_2_metadata_privatekey%"
            remote:
                entity_id: "%gssp_demo_gssp_2_remote_entity_id%"
                sso_url: "%gssp_demo_gssp_2_remote_sso_url%"
                certificate: "%gssp_demo_gssp_2_remote_certificate%"
            view_config:
                title: "%gssp_demo_gssp_2_title%"
                page_title: "%gssp_demo_gssp_2_page_title%"
                explanation: "%gssp_demo_gssp_2_explanation%"
                initiate: "%gssp_demo_gssp_2_initiate%"
                gssf_id_mismatch: "%gssp_demo_gssp_2_gssf_id_mismatch%"
