ra_saml_metadata:
    path: /authentication/metadata
    methods: [GET]
    defaults: { _controller: SurfnetStepupRaRaBundle:Saml:metadata }

ra_serviceprovider_consume_assertion:
    path: /authentication/consume-assertion
    methods: [POST]
    defaults: { _controller: SurfnetStepupRaRaBundle:Saml:consumeAssertion }

ra_vetting_search:
    path:     /
    methods: [GET, POST]
    defaults: { _controller: SurfnetStepupRaRaBundle:Vetting:startProcedure }

ra_vetting_yubikey_verify:
    path: /vetting-procedure/{procedureUuid}/verify-yubikey
    methods: [GET, POST]
    defaults: { _controller: SurfnetStepupRaRaBundle:Vetting/Yubikey:verify }
    requirements:
        procedureUuid: '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'

ra_vetting_verify_identity:
    path:     /vetting-procedure/{procedureUuid}/verify-identity
    methods:  [GET, POST]
    defaults: { _controller: SurfnetStepupRaRaBundle:Vetting:verifyIdentity }
    requirements:
        procedureUuid: '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'
