ra_saml_metadata:
    path: /authentication/metadata
    methods: [GET]
    defaults: { _controller: SurfnetStepupRaRaBundle:Saml:metadata }

ra_serviceprovider_consume_assertion:
    path: /authentication/consume-assertion
    methods: [POST]
    defaults: { _controller: SurfnetStepupRaRaBundle:Saml:consumeAssertion }

vetting_search:
    path:     /
    methods: [GET, POST]
    defaults: { _controller: SurfnetStepupRaRaBundle:Vetting:startProcedure }
