nelmio_security_report:
  path: /csp/report
  defaults: { _controller: nelmio_security.csp_reporter_controller:indexAction }
  methods: [POST]

openconext_monitor:
  resource: "@OpenConextMonitorBundle/Resources/config/routing.yml"
  prefix: /

logout:
  path: /logout
  methods: [POST]
