imports:
  - { resource: 'legacy/samlstepupproviders_parameters.yaml' }
  - { resource: 'legacy/global_view_parameters.yaml' }
  - { resource: 'legacy/parameters.yaml' }
  - { resource: 'legacy/samlstepupproviders.yaml' }



services:
  twig.extension.text: # Required by JMSTranslationBundle
    class: Twig_Extensions_Extension_Text
    tags: [{ name: twig.extension }]
