#!/bin/bash
echo "reached phplint script"
cd -c||exit
echo "${changeset.php.spacesep}" | xargs -n 1 -P 4 php -l 1>/dev/null
echo OK
## https://github.com/overtrue/phplint
#./vendor/bin/phplint --configuration=ci/qa/phplint.yaml $1