imports:
  - { resource: './services_smoketest.yaml' }

framework:
  test: ~
  session:
    storage_factory_id: session.storage.factory.mock_file
  profiler:
    collect: false
  php_errors:
    log: false # prevents user deprecated warnings
