services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Surfnet\StepupRa\SamlStepupProviderBundle\Provider\MetadataFactoryCollection:

    gssp.provider_repository:
        public: true
        class: Surfnet\StepupRa\SamlStepupProviderBundle\Provider\ProviderRepository
    Surfnet\StepupRa\SamlStepupProviderBundle\Provider\ProviderRepository:
        alias: gssp.provider_repository
