services:
    gssp.provider_repository:
        class: Surfnet\StepupRa\SamlStepupProviderBundle\Provider\ProviderRepository

    gssp.sessionbag:
        class: Symfony\Component\HttpFoundation\Session\Attribute\NamespacedAttributeBag
        factory: ['@session', 'getBag']
        arguments: ['gssp']

    gssp.session.namespaced_attribute_bag:
        public: false
        class: Symfony\Component\HttpFoundation\Session\Attribute\NamespacedAttributeBag
        arguments:
            - '__gssp__'
            - '/'
        calls:
            - [setName, ['gssp']]

    gssp.provider.collection:
        class: Surfnet\StepupRa\SamlStepupProviderBundle\Provider\ViewConfigCollection
        scope: request
